name: movemate
description: "A Monipoint Trail Project."
publish_to: 'none' 


version: 1.0.0+1
environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  haptic_feedback: ^0.5.1+1
  flutter_animate: ^4.5.2
  flex_color_scheme: ^8.1.1
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  lucide_icons: ^0.257.0
  persistent_bottom_nav_bar: ^6.2.1
  animated_flip_counter: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0





flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
      - asset: assets/fonts/Roboto-Thin.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Roboto-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Roboto-Light.ttf
        weight: 300
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 900



  assets:
    - assets/
    - assets/image/
    - assets/icon/


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
