import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

abstract final class AppTheme {
  // The defined light theme.
  static ThemeData light = FlexThemeData.light(
    colors: const FlexSchemeColor(
      // Custom colors
      primary: Color(0xFF593AA1),
      primaryContainer: Color(0xFFD0E4FF),
      secondary: Color(0xFFAC3306),
      secondaryContainer: Color(0xFFFFDBCF),
      tertiary: Color(0xFF006875),
      tertiaryContainer: Color(0xFF95F0FF),
      appBarColor: Color(0xFFFFDBCF),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
    ),
    usedColors: 1,
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffoldVariantDialog,
    blendLevel: 8,
    appBarBackground: Colors.white,
    subThemesData: const FlexSubThemesData(
      interactionEffects: true,
      bottomAppBarSchemeColor: SchemeColor.surface,
      tintedDisabledControls: true,
      blendOnLevel: 7,
      // scaffoldBackgroundSchemeColor: SchemeColor.primary,
      bottomSheetBackgroundColor: SchemeColor.transparent,
      useM2StyleDividerInM3: true,
      adaptiveSplash: FlexAdaptive.all(),
      appBarScrolledUnderElevation: 0,
      adaptiveRadius: FlexAdaptive.all(),
      adaptiveDialogRadius: FlexAdaptive.all(),
      adaptiveInputDecoratorRadius: FlexAdaptive.all(),
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 12.0,
      fabSchemeColor: SchemeColor.primary,
      chipSelectedSchemeColor: SchemeColor.primaryContainer,
      chipBlendColors: false,
      chipRadius: 26.0,
      alignedDropdown: true,
      tooltipRadius: 8,
      tooltipSchemeColor: SchemeColor.onSurface,
      tooltipOpacity: 0.81,
      useInputDecoratorThemeInDialogs: true,
      timePickerDialogRadius: 23.0,
      timePickerElementRadius: 9.0,
      snackBarElevation: 1,
      appBarCenterTitle: true,
      tabBarIndicatorSize: TabBarIndicatorSize.label,
      tabBarIndicatorWeight: 0,
      tabBarDividerColor: Color(0x00000000),
      tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
      bottomSheetRadius: 50.0,
      bottomSheetElevation: 2.0,
      bottomSheetModalElevation: 2.0,
      bottomSheetClipBehavior: Clip.hardEdge,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
      bottomNavigationBarOpacity: 0.95,
      searchBarRadius: 11.0,
      searchViewRadius: 11.0,
      navigationBarMutedUnselectedLabel: true,
      navigationBarLabelTextStyle: TextStyle(
        fontWeight: FontWeight.w500,
        fontSize: 13,
        letterSpacing: -0.4,
      ),
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainerLowest,
      navigationBarSelectedIconSchemeColor: SchemeColor.primary,
      navigationBarMutedUnselectedIcon: true,
      navigationBarIndicatorSchemeColor: SchemeColor.transparent,
      navigationBarIndicatorOpacity: 0.0,
      navigationBarOpacity: 0.96,
      navigationBarElevation: 15.0,
      navigationRailUseIndicator: true,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    keyColors: const FlexKeyColors(
      useTertiary: true,
      useExpressiveOnContainerColors: true,
    ),
    tones:
        FlexSchemeVariant.oneHue.tones(Brightness.light).higherContrastFixed(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    fontFamily: 'Roboto',
  );
  // The defined dark theme.
  static ThemeData dark = FlexThemeData.dark(
    colors: const FlexSchemeColor(
      primary: Color(0xFF493391),
      primaryContainer: Color(0xFF00325B),
      primaryLightRef: Color(0x00000000), // The color of light mode primary
      secondary: Color(0xFFFFB59D),
      secondaryContainer: Color(0xFF872100),
      secondaryLightRef: Color(0x00000000), // The color of light mode secondary
      tertiary: Color(0xFF86D2E1),
      tertiaryContainer: Color(0xFF004E59),
      tertiaryLightRef: Color(0x00000000), // The color of light mode tertiary
      appBarColor: Color(0xFFFFDBCF),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
    ),
    usedColors: 1,
    blendLevel: 7,
    appBarBackground: Color(0xFF111111),
    surface: Color(0xFF111111),
    scaffoldBackground: Color(0xFF111111),
    subThemesData: const FlexSubThemesData(
      bottomAppBarSchemeColor: SchemeColor.surface,
      adaptiveAppBarScrollUnderOff: FlexAdaptive.all(),
      interactionEffects: true,
      appBarScrolledUnderElevation: 0,
      tintedDisabledControls: true,
      blendOnColors: true,
      useM2StyleDividerInM3: true,
      adaptiveSplash: FlexAdaptive.all(),
      adaptiveRadius: FlexAdaptive.all(),
      bottomSheetBackgroundColor: SchemeColor.transparent,
      adaptiveDialogRadius: FlexAdaptive.all(),
      adaptiveInputDecoratorRadius: FlexAdaptive.all(),
      inputDecoratorBorderType: FlexInputBorderType.outline,
      inputDecoratorRadius: 12.0,
      fabSchemeColor: SchemeColor.primary,
      chipSelectedSchemeColor: SchemeColor.primaryContainer,
      chipBlendColors: false,
      chipRadius: 26.0,
      alignedDropdown: true,
      tooltipRadius: 8,
      tooltipSchemeColor: SchemeColor.onSurface,
      tooltipOpacity: 0.81,
      dialogBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
      useInputDecoratorThemeInDialogs: true,
      timePickerDialogRadius: 23.0,
      timePickerElementRadius: 9.0,
      snackBarElevation: 1,
      appBarBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
      appBarCenterTitle: true,
      tabBarItemSchemeColor: SchemeColor.primary,
      tabBarIndicatorSize: TabBarIndicatorSize.label,
      tabBarIndicatorWeight: 0,
      tabBarDividerColor: Color(0x00000000),
      tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
      bottomSheetRadius: 50.0,
      bottomSheetElevation: 2.0,
      bottomSheetModalElevation: 2.0,
      bottomSheetClipBehavior: Clip.hardEdge,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.outline,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.outline,
      navigationBarBackgroundSchemeColor: SchemeColor.surface,
      bottomNavigationBarOpacity: 0.95,
      searchBarRadius: 11.0,
      searchViewRadius: 11.0,
      navigationBarLabelTextStyle: TextStyle(
        fontWeight: FontWeight.w500,
        fontSize: 13,
        letterSpacing: -0.4,
      ),
      navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
      navigationBarMutedUnselectedLabel: true,
      navigationBarSelectedIconSchemeColor: SchemeColor.primary,
      navigationBarMutedUnselectedIcon: true,
      navigationBarIndicatorSchemeColor: SchemeColor.transparent,
      navigationBarIndicatorOpacity: 0.0,
      navigationBarOpacity: 0.96,
      navigationBarElevation: 15.0,
      navigationRailUseIndicator: true,
      navigationRailLabelType: NavigationRailLabelType.all,
    ),
    tones:
        FlexSchemeVariant.oneHue.tones(Brightness.dark).higherContrastFixed(),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
    fontFamily: 'Roboto',
  );
}
